---
title: "three-parted packages"
author: "Mason-YHY"
date: "May 21, 2019"
output: html_document
---

dplyr package test
=============================================================
```{r}
df <- data.frame(
  a = c(1:5),
  b = letters[1:5]
)
df %>% head(2)

df %>% head(2) %>% select(a)
df %>% head(2) %>% select(-a)
df %>% head(2) %>% select(a:b)
df %>% head(2) %>% select(a:b, -a)

df %>% filter(a>3)
df %>% filter(b %in% c("a", "e"))
df %>% filter(a>3, b %in% c("a", "e"))
df %>% filter(a>3 & b %in% c("a", "e"))
df %>% filter(str_detect(b, "a|e"))
```


dplyr package for group operation
==============================================================
```{r}
library(dplyr)
tbl_df(iris)
iris %>% 
  group_by(Species) %>% 
  summarize( Sepal.Width=mean(Sepal.Width), 
             Sepal.Length=mean(Sepal.Length), 
             Petal.Length=mean(Petal.Length), 
             Petal.Width=mean(Petal.Width) ) 
```


The data select function of dplyr package 
==============================================================
```{r}
iris %>% 
  select(Species, starts_with('Petal')) %>% 
  filter(Species == 'setosa') %>% tbl_df()

iris %>% 
  select(Species, ends_with('Width')) %>% 
  filter(Species == 'setosa') %>% tbl_df()
```

The data change function of dplyr package
==============================================================
```{r}
iris %>% 
  mutate(Sepal.area = pi * Sepal.Length * Sepal.Width) %>% 
  tbl_df()

iris %>% 
  transmute(Sepal.area = pi * Sepal.Length * Sepal.Width) %>% 
  tbl_df()
```

dplyr package for data join
========================================================
```{r}
x<-data.frame(Name=c("John","Paul","George","Ringo","Stuart","Pete"),instrument=c("guitar","bass","guitar","drums","bass","drums"))
y<-data.frame(name=c("John","Paul","George","Ringo","Brian"),band=c("TRUE","TRUE","TRUE","TRUE","FALSE"))


library(dplyr)
data1<-inner_join(x,y,by=c("Name"="name"))
data2<-left_join(x,y,by=c("Name"="name"))
data3<-right_join(x,y,by=c("Name"="name"))
data4<-full_join(x,y,by=c("Name"="name"))

#data5<-semi_join(x,y,by=c("Name"="name"))
#data6<-anti_join(x,y)
```


```{r}
library(readr)
even_otu_table_taxo_name_2 <- read_delim("even_otu_table_taxo_name-2.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE, 
    skip = 1)
even_otu_table_taxo_name_4 <- read_delim("even_otu_table_taxo_name-4.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE, 
    skip = 1)

summary(even_otu_table_taxo_name_2)
summary(even_otu_table_taxo_name_4)

head()
```

