---
title: "machine learning project 3"
author: "mason-YHY"
date: "2020/4/5"
output: html_document
---

1. 准备数据
```{r}
# load packages
library(mlbench)
library(caret)
library(VIM)
library(mice)
library(ggplot2)
source("caret_function.R")
# Load data
data(BreastCancer)
BreastCancer <- subset(BreastCancer, select = -Id)
aggr(BreastCancer,  prop = F, numbers = T, cex.axis = .7)
complete_data <- mice(BreastCancer, method = "pmm")
final_data <- complete(complete_data, 1)

summary_table <- data.frame(class=rep(c("row", "mice"), c(nrow(BreastCancer), nrow(final_data))), value=c(BreastCancer$Bare.nuclei, final_data$Bare.nuclei))
ggplot(data = summary_table, mapping = aes(x=value, fill=class)) + geom_density(position = "identity", alpha=0.7)
# Split out validation dataset
# create a list of 80% of the rows in the original dataset we can use for training
set.seed(7)
validationIndex <- createDataPartition(final_data$Class, p=0.80, list=FALSE)
# select 20% of the data for validation
validation <- final_data[-validationIndex,]
# use the remaining 80% of data to training and testing the models
dataset <- final_data[validationIndex,]
```

2. 模型比较
```{r}
# 10-fold cross validation with 3 repeats
trainControl <- trainControl(method="repeatedcv", number=10, repeats=3)
# "nb"" method error
select_m <- c("glm", "lda", "knn", "rpart", "svmRadial", "rf", "gbm", "C5.0")
train_result <- parallel_train(selected_m = select_m, train_data = dataset, predict_var = "Class", trainControl = trainControl, metric = "Accuracy")
train_result_summary <- resamples(train_result)
summary(train_result_summary)
dotplot(train_result_summary)
```

3. 对表现最好的模型进行调参
```{r}
set.seed(7)
grid <- expand.grid(.sigma=c(0.025, 0.05, 0.1, 0.15), .C=seq(1, 10, by=1))
fit.svm <- train(Class~., data=dataset, method="svmRadial", metric="Accuracy", tuneGrid=grid,
preProc=c("BoxCox"), trControl=trainControl)
print(fit.svm)
plot(fit.svm)
```

4. 验证集进行验证
```{r}
importance <- varImp(fit.svm, scale = F)
plot(importance)
final_model <- fit.svm$finalModel
predictions <- predict(fit.svm, validation)
confusionMatrix(predictions, validation$Class)
```


